# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fib(maxValue):
    x = 1
    y = 2
    group = list()
    while x <= maxValue:
        group.append(x)
        z = x + y
        x = y
        y = z
    return group

sum = 0
fibonacciNum = fib(4000000)
for x in fibonacciNum:
    if x % 2 == 0:
        sum += x
print(sum)